persistence:
  destbackup:
    enabled: true
    type: pvc
    mountPath: /backedup
    targetSelectAll: true
    volsync:
      - name: mybackup
        type: restic
        credentials: mys3
        dest:
          enabled: true
        src:
          enabled: false

credentials:
  mys3:
    type: s3
    url: ""
    region: ""
    bucket: ""
    accessKey: ""
    secretKey: ""
    encrKey: ""
